pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn deploy'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t coit-backend1-v5 .'
               sh 'docker images'
            }
        }    
        stage('run-container') {
            steps {
               sh 'docker run -d -p 9999:8080 coit-backend1-v5'
               sh 'sleep 20'
               sh 'docker ps'
            }
        }    
        stage('stop-container') {
            steps {
               script {
                       def CONTAINER_ID = sh(returnStdout: true, script: 'docker ps | grep "coit" | awk '{print $1}'')
                  }
        }    
        stage('remove-image') {
            steps {
               sh 'docker stop $CONTAINER_ID'
               sh 'docker ps -a'
               sh 'docker rm $CONTAINER_ID'
               sh 'docker images'
               sh 'docker tag coit-backend1:v5 shivaji5897/coit-backend111:v5'
               sh 'docker push shivaji5897/coit-backend111:v5'
               sh 'docker rmi shivaji5897/coit-backend111:v5'
               //sh 'IMAGE_ID=`docker images -a | grep "coit" | awk '{print $3}'`'
            }                 
        }
        stage('stop-container') {
            steps {
               script{
                       IMAGE_ID=docker images -a | grep "coit" | awk '{print $3}'
                     }
                  }
        }
        stage('remove-image'){
            steps {
                sh 'docker rmi $IMAGE_ID'
            }
        }
    }
}
