pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn deploy'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t coit-backend1-v5 .'
               sh 'docker images'
            }
        }    
        stage('run-container') {
            steps {
               sh 'docker run -d -p 9999:8080 coit-backend1-v5'
               sh 'sleep 20'
               sh 'docker ps'
            }
        }    
        stage('container-id') {
            steps {
               withEnv(['container_id=docker ps | grep "java" | awk \'{print $1}\'']) {
               echo "container_id: ${container_id}"
}
        }  
        }
        stage('remove-container') {
            steps {
               sh 'docker stop $container_id'
               sh 'docker ps -a'
               sh 'docker rm $container_id'
               sh 'docker images'
               sh 'docker tag coit-backend1:v5 shivaji5897/coit-backend111:v5'
               sh 'docker push shivaji5897/coit-backend111:v5'
               sh 'docker rmi shivaji5897/coit-backend111:v5'
               //sh 'IMAGE_ID=`docker images -a | grep "coit" | awk '{print $3}'`'
            }                 
        }
        stage('image-id') {
            steps {
              withEnv(['image_id=docker images -a | grep "coit" | awk \'{print $3}\'']) {
              echo "image_id: ${image_id}"
}
                  }
        }
        stage('remove-image'){
            steps {
                sh 'docker rmi $image_id'
            }
        }
    }
}
